import { chromium } from 'playwright';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
await page.goto('http://127.0.0.1:5199/', { waitUntil: 'domcontentloaded' });
await page.waitForTimeout(2500);
const agree = page.locator('text=我已了解，放心使用').first();
if (await agree.isVisible().catch(() => false)) await agree.click();
await page.waitForTimeout(500);
await page.locator('button:has-text("PDF 工坊")').first().click();
await page.waitForTimeout(900);
const favBtn = page.locator('button[aria-label="收藏此工具"]').first();
await favBtn.click();
await page.waitForTimeout(300);
await page.locator('button[title="欢迎来到 ZonScale"]').first().click();
await page.waitForTimeout(800);
const chip = page.locator('button:has-text("页面整理")').first();
console.log('chip visible:', await chip.isVisible());
await chip.click();
await page.waitForTimeout(1200);
console.log('url hash:', page.url());
const welcome = await page.locator('text=欢迎来到 ZonScale').first().isVisible().catch(() => false);
console.log('still on home?', welcome);
const subnav = await page.evaluate(() => {
  const pills = [...document.querySelectorAll('.zs-mobile-scroll-x')];
  return pills.map(p => p.textContent.slice(0, 80));
});
console.log('subnav:', JSON.stringify(subnav));
await browser.close();
