import { chromium } from 'playwright';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
await page.goto('http://127.0.0.1:5199/', { waitUntil: 'domcontentloaded' });
await page.waitForTimeout(2500);
const agree = page.locator('text=我已了解，放心使用').first();
if (await agree.isVisible().catch(() => false)) await agree.click();
await page.waitForTimeout(500);
await page.locator('button:has-text("PDF 工坊")').first().click();
await page.waitForTimeout(900);
await page.locator('button[aria-label="收藏此工具"]').first().click();
await page.waitForTimeout(300);
await page.locator('button[title="欢迎来到 ZonKey"]').first().click();
await page.waitForTimeout(800);
await page.locator('button:has-text("页面整理")').first().click();
await page.waitForTimeout(1200);
// 点击「页面整理」后应落在 pdf_center + pdf-organize（不是 pdf-home）
const bodyText = await page.evaluate(() => document.body.innerText.slice(0, 400));
console.log(bodyText);
await browser.close();
